### ISSUE TITLE
Easy Simulation

### ISSUE THREAD

**Issue by musicianZem** [Joowon0/baekjoon#1]
BOJ 1614 YJ's finger maybe fun ! :+1:

**Comment by joowon-byun** [comment]
This isn't algorithm prob..
I got wrong 2 times 'cause it require long long type :(

**Comment by joowon-byun** [comment]
Thanx anyway :+1:

**Comment by musicianZem** [comment]
이런 타입의 프로그래밍도 나오더라구요... 시킨대로 짜기!?
물론 type도 고려해야함..,,.,.,.....
바쁜기간이실테니 화이팅하시길바랍니

**Comment by musicianZem** [comment]
heart finger count <= 1000000000. ( almost INTMAX/2 )
so, max count <= 5000000000.       ( > INTMAX )
on programming test, these informations are hide in problem.
even, you don't know right or wrong because simple testcase don't include this cases.
그래서 시켜보기도 한거고?...히히 화이팅
